import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
  // Manually create a sidebar
    'overview',
    'intro', // Reference to a Markdown file named 'intro.md'
    'trading_signal_analysis',
    'license',
    {
      type: 'category',
      label: 'Menu Installation',
      items: [
        'menu-installation/create-bot', // Reference to 'docs/menu-installation/install-python.md'
        'menu-installation/install-postgres', // Reference to 'docs/menu-installation/install-postgres.md'
        'menu-installation/install-app', // Reference to 'docs/menu-installation/install-postgres.md'
        'menu-installation/congratulations', // Reference to 'docs/menu-installation/congratulations.md'
      ],
    },
    {
      type: 'category',
      label: 'Menu Options',
      items: [
        'menu-options/run-backtest', // Reference to 'docs/menu-options/congratulations.md'
        'menu-options/reset-trader',
        'menu-options/start-stop-bot',
        'menu-options/start-stop-signals',
        'menu-options/gainers-analisys',
        'menu-options/auto-trade-gainers',
        'menu-options/technicall-analisys',
        'menu-options/manual-trade-gainers',
        'menu-options/elliot-waves-analisys',
        'menu-options/list-menu',
        'menu-options/congratulations',
      ],
    },
  ],
   
};

export default sidebars;
